name: Firebase Dev CD

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: npm i
      - run: npm run build
        env:
          CI: false
      - uses: w9jds/firebase-action@v2.0.0
        with:
          args: hosting:channel:deploy convo-dev
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
